version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      # важно: из контейнера "localhost" = сам контейнер, поэтому указываем имя сервиса backend
      NEXT_PUBLIC_API_BASE_URL: "http://backend:8000"
    ports:
      - "3000:3000"
